apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opendrive
type: Opaque
stringData:
  POSTGRES_DB: opendrive_db
  POSTGRES_USER: opendrive_user
  POSTGRES_PASSWORD: Drive2025!Secure